
name: Test & Deploy
on: 
    push:
        branches:
             main
    pull_request:
        branches:
            main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2

      - name: Use PostgreSQL
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: 'nc_games_test'
          postgresql user: 'postgres'
          postgresql password: 'Ncoder97'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: PGDATABASE=nc_games_test PGUSER=postgres PGPASSWORD=Ncoder97 npm t       
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: 40116102-5c84-4e26-84ba-ce6a3a77c2ba
          heroku_app_name: artehs-games
          heroku_email: artehrush@gmail.com

